---
secure:
  required_reviews: 1
  requires_mfa: true
  requires_verified: true
  upstream_repository: base-org/onchainsummer.xyz

build:
  engines:
    - BaldurECR:
        name: onchainsummer
        path: ./Dockerfile
    - BaldurECR:
        name: cdnsync
        path: ./Dockerfile.cdnsync

operate:
  slack_channels:
    - "#base-codeflow-notifications"
