import TrendingImage1 from '../../public/trending/trending-temp/image-1.png'
import TrendingImage2 from '../../public/trending/trending-temp/image-2.png'
import TrendingImage3 from '../../public/trending/trending-temp/image-3.png'
import TrendingImage4 from '../../public/trending/trending-temp/image-4.png'
import TrendingImage5 from '../../public/trending/trending-temp/image-5.png'
import TrendingImage6 from '../../public/trending/trending-temp/image-6.png'
import TrendingImage7 from '../../public/trending/trending-temp/image-7.png'

export const trending = [
  {
    id: 1,
    title: 'Bear Market Builders',
    subTitle: 'Bearbuilder.eth ',
    numMints: 500,
    price: '0.0004',
    images: [
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
    ],
  },
  {
    id: 2,
    title: 'Bear Market Builders',
    subTitle: 'Bearbuilder.eth ',
    numMints: 500,
    price: '0.0004',
    images: [
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
    ],
  },
  {
    id: 3,
    title: 'Bear Market Builders',
    subTitle: 'Bearbuilder.eth ',
    numMints: 500,
    price: '0.0004',
    images: [
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
    ],
  },
  {
    id: 4,
    title: 'Bear Market Builders',
    subTitle: 'Bearbuilder.eth ',
    numMints: 500,
    price: '0.0004',
    images: [
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
    ],
  },
  {
    id: 5,
    title: 'Bear Market Builders',
    subTitle: 'Bearbuilder.eth ',
    numMints: 500,
    price: '0.0004',
    images: [
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
    ],
  },
  {
    id: 6,
    title: 'Bear Market Builders',
    subTitle: 'Bearbuilder.eth ',
    numMints: 500,
    price: '0.0004',
    images: [
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
    ],
  },
  {
    id: 7,
    title: 'Bear Market Builders',
    subTitle: 'Bearbuilder.eth ',
    numMints: 500,
    price: '0.0004',
    images: [
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
      TrendingImage1,
      TrendingImage2,
      TrendingImage3,
      TrendingImage4,
      TrendingImage5,
      TrendingImage6,
      TrendingImage7,
    ],
  },
]
