import { Partner } from './types'
import { CAMPAIGN_HOUR, CAMPAIGN_MINUTE } from '@/config/constants'
import { MintType } from '@/components/MintDialog/types'

const indelible: Partner = {
  slug: 'indelible',
  name: 'Indelible',
  url: 'https://indelible.xyz/',
  description:
    "Collect art curated by Indelible Labs and learn how they're empowering artists who want to take their ideas onchain.",
  brandColor: 'rgb(0, 224, 191)',
  icon: '/partners/indelible/icon.png',
  banner: '/partners/indelible/banner-icon.svg',
  aarweaveDigest: 'XzNUxTbsDb-TbDEEloEHTfRfKPDpVSXAKfORPTfj9zc',
  twitter: '@indelible_labs',
  drops: [
    {
      image: '/partners/indelible/drops/drop-1.jpeg',
      creator: '0xd444448ed791De5c3635280D78D60d15E34fb73f',
      name: 'Degenerate Ape Academy: The Guardian',
      address: '0x0',
      description:
        'The Degenerate Ape Academy stands with Coinbase as they fight for the future of crypto.',
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/degenapeacademy',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 22, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.01',
    },
    {
      image: '/partners/indelible/drops/drop-2.gif',
      creator: '0x63989a803b61581683B54AB6188ffa0F4bAAdf28',
      name: 'Pablo Stanley: Scoot',
      address: '0x0',
      description: `Hola, I'm Pabs, and I've turned a fun moment from my comics into a gif - just Pabs and Rupert, cruising on a scooter.`,
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/pablostanley',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 23, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.001',
    },
    {
      image: '/partners/indelible/drops/drop-3.jpeg',
      creator: '0x759c4ebebe5071db56c78b6c7bae53c15cb2f6d8',
      name: 'Amber Vittoria: Learning To Double Dutch',
      address: '0x0',
      description: `This digital piece, by Amber Vittoria, is inspired by carrying multiple emotions simultaneously, and the beauty within the complexity of emotion itself.`,
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/ambervittoria',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 22, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.001',
    },
    {
      image: '/partners/indelible/drops/drop-4.png',
      creator: '0xb70cc02cbd58c313793c971524ad066359fd1e8e',
      name: 'PIV: Glass Punk',
      address: '0x0',
      description: `Most of my work has a connection to the iconic CryptoPunks in some way. This is no different here.`,
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/piv',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 22, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.001',
    },
    {
      image: 'https://assets.onchainsummer.xyz/indelible-drop-5.mp4',
      creator: '0xA0E1B198bCC877a950A29512ab5C0CE1Bb964c97',
      name: 'Spottie WiFi ft. Jim Jones: Buy the Dips',
      address: '0x0',
      description: `Spottie WiFi recruits legend Jim Jones for "Buy the Dips," the latest single from Spottie's album "The King's Alpha".`,
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/spottiewifi',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 22, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.0025',
    },
    {
      image: 'https://assets.onchainsummer.xyz/indelible-drop-6.mp4',
      creator: '0x77037050bb27ae8f09118a0c480224d897589c65',
      name: 'ARTJEDI1: Pavlovian Instinct',
      address: '0x0',
      description: `ARTJEDI1 a.k.a Bea Kayani, brings the themes of memory, reaction, and reflection through evocative imagery.`,
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/artjedi1',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 22, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.0055',
    },
  ],
}

export default indelible
