import { Partner } from './types'
import { CAMPAIGN_HOUR, CAMPAIGN_MINUTE } from '@/config/constants'
import { MintType } from '@/components/MintDialog/types'

const indelible: Partner = {
  slug: 'indelible',
  name: 'Indelible',
  url: 'https://indelible.xyz/',
  description:
    "Collect art curated by Indelible Labs and learn how they're empowering artists who want to take their ideas onchain.",
  brandColor: 'rgb(0, 224, 191)',
  icon: '/partners/indelible/icon.png',
  banner: '/partners/indelible/banner-icon.svg',
  aarweaveDigest: 'XzNUxTbsDb-TbDEEloEHTfRfKPDpVSXAKfORPTfj9zc',
  twitter: '@indelible_labs',
  drops: [
    {
      image: '/partners/indelible/drops/drop-1.jpeg',
      creator: '0xd444448ed791De5c3635280D78D60d15E34fb73f',
      name: 'Degenerate Ape Academy: The Guardian',
      address: '0x0',
      description:
        'The Degenerate Ape Academy stands with Coinbase as they fight for the future of crypto.',
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/degenapeacademy',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 22, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.01',
    },
    {
      image: '/partners/indelible/drops/drop-2.gif',
      creator: '0x63989a803b61581683B54AB6188ffa0F4bAAdf28',
      name: 'Pablo Stanley: Pabs and Rupert Scootin',
      address: '0x0',
      description: `Hola, I'm Pabs, and I've taken a fun little moment from my comics and turned it into a looped gif. It's just Pabs and Rupert, cruising on a scooter. Trying to keep things simple with the black-and-white doodle charm I always go for in my comics.  This is kinda special for me. It’s the first time I’m minting something from my comic world and the first time in Base. If you’ve been following my comics, you know the vibes. If not, well, here’s a little taste of Pabs and Rupert. Hope it brings a smile to your face!`,
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/pablostanley',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 23, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.001',
    },
    {
      image: '/partners/indelible/drops/drop-3.jpeg',
      creator: '0x759c4ebebe5071db56c78b6c7bae53c15cb2f6d8',
      name: 'Amber Vittoria: Learning To Double Dutch',
      address: '0x0',
      description: `This digital piece, by Amber Vittoria, is inspired by carrying multiple emotions simultaneously, and the beauty within the complexity of emotion itself.`,
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/ambervittoria',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 22, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.001',
    },
    {
      image: '/partners/indelible/drops/drop-4.png',
      creator: '0xb70cc02cbd58c313793c971524ad066359fd1e8e',
      name: 'PIV: Glass Punk',
      address: '0x0',
      description: `Most of my work has a connection to the iconic CryptoPunks in some way. This is no different here. In the spirit of affordable NFTs on a layer 2 network with small fees, I wanted to make something very light and ephemeral. Hence, Glass Punk, an NFT without background, composed of less than 200 pixels that are mostly transparent.  At the same time, the piece refers to something that artists have done over and over again over the centuries, to show off their skills and for the joy of doing it: the fine art of rendering difficult materials, be it transparent, reflective objects (glass) or fabric folds either draped over a model or as a valid content area in and of itself.`,
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/piv',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 22, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.001',
    },
    {
      image: '',
      creator: '0xA0E1B198bCC877a950A29512ab5C0CE1Bb964c97',
      name: 'Spottie WiFi ft. Jim Jones: Buy the Dips',
      address: '0x0',
      description: `CryptoPunk rapper Spottie WiFi recruits the legend Jim Jones for "Buy the Dips," the latest single from Spottie's album "The King's Alpha." The song and the album are now streaming on all platforms.`,
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/spottiewifi',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 22, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.0025',
    },
    {
      image: '',
      creator: '0x77037050bb27ae8f09118a0c480224d897589c65',
      name: 'ARTJEDI1: Pavlovian Instinct',
      address: '0x0',
      description: ` "Pavlovian Instinct" might suggest a behaviour that feels instinctual but is really learned through conditioning. ARTJEDI1 a.k.a Bea Kayani, brings the themes of memory, reaction, and reflection through evocative imagery inviting contemplation about the essence of involuntary responses and deep-seated memories evoked by familiar stimuli.    The artwork is an intricate photo-collage of mundane water reflections, created in 2013, minted Onchain 2023. The artist travelled across continents and collected water reflections for 15 years as a measure of personal healing and in an attempt to document beauty in minute spaces in water & ephemeral phenomenons. The compositions created in situ in collaboration with the nature itself, the colours are often raw; final works bridge the abstract and the figurative; artist’s own visual language inspired by Eastern and Western influences, creating Rorschach like images that leave open the vistas of imagination for the viewers to make it a part of their own chaos.`,
      crossMintClientId: '',
      mintType: MintType.External,
      externalLink: 'https://indelible.xyz/mint/artjedi1',
      type: 'external',
      startDate: Date.UTC(2023, 7, 20, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      endDate: Date.UTC(2023, 7, 22, CAMPAIGN_HOUR, CAMPAIGN_MINUTE, 0, 0),
      price: '0.0055',
    },
  ],
}

export default indelible
