#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "Don't commit to master - it's bad juju"
  exit 1
fi

# yarn lint-staged
